# Generated by Django 3.0.2 on 2020-02-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_home', '0002_auto_20200208_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
